# Generated by Django 5.2.7 on 2026-04-11 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('magazine_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('weekday_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weekend_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(default='demo@123', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='core.area')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(default='demo@123', max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.area')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('note', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='DailyIndent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('checked_by_admin', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indents', to='core.area')),
                ('executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_indents', to='core.executive')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indents', to='core.vendor')),
            ],
            options={
                'ordering': ['-date', 'vendor__name'],
                'unique_together': {('vendor', 'date')},
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checked', 'Checked')], default='pending', max_length=20)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.vendor')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyIndentMagazineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('daily_indent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_items', to='core.dailyindent')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.magazine')),
            ],
            options={
                'unique_together': {('daily_indent', 'magazine')},
            },
        ),
        migrations.CreateModel(
            name='AreaMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_magazines', to='core.area')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_areas', to='core.magazine')),
            ],
            options={
                'unique_together': {('area', 'magazine')},
            },
        ),
        migrations.CreateModel(
            name='DailyIndentNewspaperItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('daily_indent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspaper_items', to='core.dailyindent')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newspaper')),
            ],
            options={
                'unique_together': {('daily_indent', 'newspaper')},
            },
        ),
        migrations.CreateModel(
            name='AreaNewspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_newspapers', to='core.area')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspaper_areas', to='core.newspaper')),
            ],
            options={
                'unique_together': {('area', 'newspaper')},
            },
        ),
        migrations.CreateModel(
            name='VendorMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('stopped_from', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_vendors', to='core.magazine')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_magazines', to='core.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'magazine')},
            },
        ),
        migrations.CreateModel(
            name='VendorNewspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('stopped_from', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspaper_vendors', to='core.newspaper')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_newspapers', to='core.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'newspaper')},
            },
        ),
    ]
