# Generated by Django 5.2.7 on 2026-04-02 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MagazinePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewspaperPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('weekday_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weekend_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(default='demo', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(default='demo', max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.vendor')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyIndent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('udayavani', models.PositiveIntegerField(default=0)),
                ('enadu', models.PositiveIntegerField(default=0)),
                ('dnk', models.PositiveIntegerField(default=0)),
                ('sakshi', models.PositiveIntegerField(default=0)),
                ('b_standard', models.PositiveIntegerField(default=0)),
                ('k_prabha', models.PositiveIntegerField(default=0)),
                ('sk', models.PositiveIntegerField(default=0)),
                ('tharanga', models.PositiveIntegerField(default=0)),
                ('karma_veera', models.PositiveIntegerField(default=0)),
                ('tushara', models.PositiveIntegerField(default=0)),
                ('roopathara', models.PositiveIntegerField(default=0)),
                ('returned_udayavani', models.PositiveIntegerField(default=0)),
                ('returned_enadu', models.PositiveIntegerField(default=0)),
                ('returned_dnk', models.PositiveIntegerField(default=0)),
                ('returned_sakshi', models.PositiveIntegerField(default=0)),
                ('returned_b_standard', models.PositiveIntegerField(default=0)),
                ('returned_k_prabha', models.PositiveIntegerField(default=0)),
                ('returned_sk', models.PositiveIntegerField(default=0)),
                ('returned_tharanga', models.PositiveIntegerField(default=0)),
                ('returned_karma_veera', models.PositiveIntegerField(default=0)),
                ('returned_tushara', models.PositiveIntegerField(default=0)),
                ('returned_roopathara', models.PositiveIntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indents', to='core.vendor')),
            ],
            options={
                'ordering': ['-date', 'vendor__name'],
                'unique_together': {('vendor', 'date')},
            },
        ),
    ]
