# Generated by Django 5.2.7 on 2026-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyindent',
            name='cash_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
