# Generated by Django 5.2.7 on 2026-05-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailyindentmagazineitem_cash_collected'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_mappings', to='core.executive')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_mappings', to='core.vendor')),
            ],
            options={
                'unique_together': {('executive', 'vendor')},
            },
        ),
    ]
