# Generated by Django 5.2.7 on 2026-05-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_executivevendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyindent',
            options={'ordering': ['date', 'vendor__name']},
        ),
        migrations.AddField(
            model_name='dailyindent',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailyindent',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailyindentmagazineitem',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailyindentmagazineitem',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
